//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace ExpostatsExcel2013AddIn {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(4)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class Feuil3 : Microsoft.Office.Tools.Excel.WorksheetBase {
        
        internal Microsoft.Office.Tools.Excel.NamedRange AIHA_User;
        
        internal Microsoft.Office.Tools.Excel.NamedRange AM_est;
        
        internal Microsoft.Office.Tools.Excel.NamedRange AM_ucl70;
        
        internal Microsoft.Office.Tools.Excel.NamedRange AM_ucl95;
        
        internal Microsoft.Office.Tools.Excel.NamedRange authors;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Authors_Copyright;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Choice_GrVal;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Choice_language;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Confidence;
        
        internal Microsoft.Office.Tools.Excel.NamedRange count_IC;
        
        internal Microsoft.Office.Tools.Excel.NamedRange dddd;
        
        internal Microsoft.Office.Tools.Excel.NamedRange disclaimer;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Exc_est;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Exc_ucl70;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Exc_ucl95;
        
        internal Microsoft.Office.Tools.Excel.NamedRange ExcelVersion;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Final_valid;
        
        internal Microsoft.Office.Tools.Excel.NamedRange GM_est;
        
        internal Microsoft.Office.Tools.Excel.NamedRange GM_ucl;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Gr_Val;
        
        internal Microsoft.Office.Tools.Excel.NamedRange GSD_est;
        
        internal Microsoft.Office.Tools.Excel.NamedRange GSD_ucl;
        
        internal Microsoft.Office.Tools.Excel.NamedRange List_Language;
        
        internal Microsoft.Office.Tools.Excel.NamedRange List_Resolution;
        
        internal Microsoft.Office.Tools.Excel.NamedRange MeanLogT;
        
        internal Microsoft.Office.Tools.Excel.NamedRange OS_Version;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Perc95_est;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Percentile;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Resolution;
        
        internal Microsoft.Office.Tools.Excel.NamedRange StdLogT;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Tb_Chr_nb;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Tb_Gr_Val;
        
        internal Microsoft.Office.Tools.Excel.NamedRange Title_Example;
        
        internal Microsoft.Office.Tools.Excel.NamedRange UTL70_est;
        
        internal Microsoft.Office.Tools.Excel.NamedRange UTL95_est;
        
        internal Microsoft.Office.Tools.Excel.NamedRange version;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Feuil3(global::Microsoft.Office.Tools.Excel.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "Feuil3", "Feuil3") {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            Globals.Feuil3 = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
            this.AIHA_User.BeginInit();
            this.AM_est.BeginInit();
            this.AM_ucl70.BeginInit();
            this.AM_ucl95.BeginInit();
            this.authors.BeginInit();
            this.Authors_Copyright.BeginInit();
            this.Choice_GrVal.BeginInit();
            this.Choice_language.BeginInit();
            this.Confidence.BeginInit();
            this.count_IC.BeginInit();
            this.dddd.BeginInit();
            this.disclaimer.BeginInit();
            this.Exc_est.BeginInit();
            this.Exc_ucl70.BeginInit();
            this.Exc_ucl95.BeginInit();
            this.ExcelVersion.BeginInit();
            this.Final_valid.BeginInit();
            this.GM_est.BeginInit();
            this.GM_ucl.BeginInit();
            this.Gr_Val.BeginInit();
            this.GSD_est.BeginInit();
            this.GSD_ucl.BeginInit();
            this.List_Language.BeginInit();
            this.List_Resolution.BeginInit();
            this.MeanLogT.BeginInit();
            this.OS_Version.BeginInit();
            this.Perc95_est.BeginInit();
            this.Percentile.BeginInit();
            this.Resolution.BeginInit();
            this.StdLogT.BeginInit();
            this.Tb_Chr_nb.BeginInit();
            this.Tb_Gr_Val.BeginInit();
            this.Title_Example.BeginInit();
            this.UTL70_est.BeginInit();
            this.UTL95_est.BeginInit();
            this.version.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.version.EndInit();
            this.UTL95_est.EndInit();
            this.UTL70_est.EndInit();
            this.Title_Example.EndInit();
            this.Tb_Gr_Val.EndInit();
            this.Tb_Chr_nb.EndInit();
            this.StdLogT.EndInit();
            this.Resolution.EndInit();
            this.Percentile.EndInit();
            this.Perc95_est.EndInit();
            this.OS_Version.EndInit();
            this.MeanLogT.EndInit();
            this.List_Resolution.EndInit();
            this.List_Language.EndInit();
            this.GSD_ucl.EndInit();
            this.GSD_est.EndInit();
            this.Gr_Val.EndInit();
            this.GM_ucl.EndInit();
            this.GM_est.EndInit();
            this.Final_valid.EndInit();
            this.ExcelVersion.EndInit();
            this.Exc_ucl95.EndInit();
            this.Exc_ucl70.EndInit();
            this.Exc_est.EndInit();
            this.disclaimer.EndInit();
            this.dddd.EndInit();
            this.count_IC.EndInit();
            this.Confidence.EndInit();
            this.Choice_language.EndInit();
            this.Choice_GrVal.EndInit();
            this.Authors_Copyright.EndInit();
            this.authors.EndInit();
            this.AM_ucl95.EndInit();
            this.AM_ucl70.EndInit();
            this.AM_est.EndInit();
            this.AIHA_User.EndInit();
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.AIHA_User = Globals.Factory.CreateNamedRange(null, null, "AIHA_User", "AIHA_User", this);
            this.AM_est = Globals.Factory.CreateNamedRange(null, null, "AM_est", "AM_est", this);
            this.AM_ucl70 = Globals.Factory.CreateNamedRange(null, null, "AM_ucl70", "AM_ucl70", this);
            this.AM_ucl95 = Globals.Factory.CreateNamedRange(null, null, "AM_ucl95", "AM_ucl95", this);
            this.authors = Globals.Factory.CreateNamedRange(null, null, "authors", "authors", this);
            this.Authors_Copyright = Globals.Factory.CreateNamedRange(null, null, "Authors_Copyright", "Authors_Copyright", this);
            this.Choice_GrVal = Globals.Factory.CreateNamedRange(null, null, "Choice_GrVal", "Choice_GrVal", this);
            this.Choice_language = Globals.Factory.CreateNamedRange(null, null, "Choice_language", "Choice_language", this);
            this.Confidence = Globals.Factory.CreateNamedRange(null, null, "Confidence", "Confidence", this);
            this.count_IC = Globals.Factory.CreateNamedRange(null, null, "count_IC", "count_IC", this);
            this.dddd = Globals.Factory.CreateNamedRange(null, null, "dddd", "dddd", this);
            this.disclaimer = Globals.Factory.CreateNamedRange(null, null, "disclaimer", "disclaimer", this);
            this.Exc_est = Globals.Factory.CreateNamedRange(null, null, "Exc_est", "Exc_est", this);
            this.Exc_ucl70 = Globals.Factory.CreateNamedRange(null, null, "Exc_ucl70", "Exc_ucl70", this);
            this.Exc_ucl95 = Globals.Factory.CreateNamedRange(null, null, "Exc_ucl95", "Exc_ucl95", this);
            this.ExcelVersion = Globals.Factory.CreateNamedRange(null, null, "ExcelVersion", "ExcelVersion", this);
            this.Final_valid = Globals.Factory.CreateNamedRange(null, null, "Final_valid", "Final_valid", this);
            this.GM_est = Globals.Factory.CreateNamedRange(null, null, "GM_est", "GM_est", this);
            this.GM_ucl = Globals.Factory.CreateNamedRange(null, null, "GM_ucl", "GM_ucl", this);
            this.Gr_Val = Globals.Factory.CreateNamedRange(null, null, "Gr_Val", "Gr_Val", this);
            this.GSD_est = Globals.Factory.CreateNamedRange(null, null, "GSD_est", "GSD_est", this);
            this.GSD_ucl = Globals.Factory.CreateNamedRange(null, null, "GSD_ucl", "GSD_ucl", this);
            this.List_Language = Globals.Factory.CreateNamedRange(null, null, "List_Language", "List_Language", this);
            this.List_Resolution = Globals.Factory.CreateNamedRange(null, null, "List_Resolution", "List_Resolution", this);
            this.MeanLogT = Globals.Factory.CreateNamedRange(null, null, "MeanLogT", "MeanLogT", this);
            this.OS_Version = Globals.Factory.CreateNamedRange(null, null, "OS_Version", "OS_Version", this);
            this.Perc95_est = Globals.Factory.CreateNamedRange(null, null, "Perc95_est", "Perc95_est", this);
            this.Percentile = Globals.Factory.CreateNamedRange(null, null, "Percentile", "Percentile", this);
            this.Resolution = Globals.Factory.CreateNamedRange(null, null, "Resolution", "Resolution", this);
            this.StdLogT = Globals.Factory.CreateNamedRange(null, null, "StdLogT", "StdLogT", this);
            this.Tb_Chr_nb = Globals.Factory.CreateNamedRange(null, null, "Tb_Chr_nb", "Tb_Chr_nb", this);
            this.Tb_Gr_Val = Globals.Factory.CreateNamedRange(null, null, "Tb_Gr_Val", "Tb_Gr_Val", this);
            this.Title_Example = Globals.Factory.CreateNamedRange(null, null, "Title_Example", "Title_Example", this);
            this.UTL70_est = Globals.Factory.CreateNamedRange(null, null, "UTL70_est", "UTL70_est", this);
            this.UTL95_est = Globals.Factory.CreateNamedRange(null, null, "UTL95_est", "UTL95_est", this);
            this.version = Globals.Factory.CreateNamedRange(null, null, "version", "version", this);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown() {
            this.version.Dispose();
            this.UTL95_est.Dispose();
            this.UTL70_est.Dispose();
            this.Title_Example.Dispose();
            this.Tb_Gr_Val.Dispose();
            this.Tb_Chr_nb.Dispose();
            this.StdLogT.Dispose();
            this.Resolution.Dispose();
            this.Percentile.Dispose();
            this.Perc95_est.Dispose();
            this.OS_Version.Dispose();
            this.MeanLogT.Dispose();
            this.List_Resolution.Dispose();
            this.List_Language.Dispose();
            this.GSD_ucl.Dispose();
            this.GSD_est.Dispose();
            this.Gr_Val.Dispose();
            this.GM_ucl.Dispose();
            this.GM_est.Dispose();
            this.Final_valid.Dispose();
            this.ExcelVersion.Dispose();
            this.Exc_ucl95.Dispose();
            this.Exc_ucl70.Dispose();
            this.Exc_est.Dispose();
            this.disclaimer.Dispose();
            this.dddd.Dispose();
            this.count_IC.Dispose();
            this.Confidence.Dispose();
            this.Choice_language.Dispose();
            this.Choice_GrVal.Dispose();
            this.Authors_Copyright.Dispose();
            this.authors.Dispose();
            this.AM_ucl95.Dispose();
            this.AM_ucl70.Dispose();
            this.AM_est.Dispose();
            this.AIHA_User.Dispose();
            base.OnShutdown();
        }
    }
    
    internal sealed partial class Globals {
        
        private static Feuil3 _Feuil3;
        
        internal static Feuil3 Feuil3 {
            get {
                return _Feuil3;
            }
            set {
                if ((_Feuil3 == null)) {
                    _Feuil3 = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
    }
}
